// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE7NtHoEKyXZb3rWsi-LTbL--g1CpBzr4',
    appId: '1:624268864963:web:339dd3951538faa390a176',
    messagingSenderId: '624268864963',
    projectId: 'f-reddit-e0bd1',
    authDomain: 'f-reddit-e0bd1.firebaseapp.com',
    storageBucket: 'f-reddit-e0bd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1EW3T1dJqjWKcsbWOJDcqxz_1ujtGMk0',
    appId: '1:624268864963:android:4d8c1b53d2c6811790a176',
    messagingSenderId: '624268864963',
    projectId: 'f-reddit-e0bd1',
    storageBucket: 'f-reddit-e0bd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGi9S_JAL_gUB7Jgiw-rixdn_jw8SoNuE',
    appId: '1:624268864963:ios:c709a49b979e4bd690a176',
    messagingSenderId: '624268864963',
    projectId: 'f-reddit-e0bd1',
    storageBucket: 'f-reddit-e0bd1.appspot.com',
    iosBundleId: 'com.example.fReddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGi9S_JAL_gUB7Jgiw-rixdn_jw8SoNuE',
    appId: '1:624268864963:ios:2c046358f50dfa8090a176',
    messagingSenderId: '624268864963',
    projectId: 'f-reddit-e0bd1',
    storageBucket: 'f-reddit-e0bd1.appspot.com',
    iosBundleId: 'com.example.fReddit.RunnerTests',
  );
}
